# Generated by Django 3.0.5 on 2020-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnote',
            name='notecontent',
            field=models.TextField(blank=True),
        ),
    ]
